<?php include $_SERVER['DOCUMENT_ROOT']."/includes/header.php"; ?>



  <div id="coverSection" class="coversectionaboutus">
    <div class="covercontainerprimary w-container">
      <div data-ix="new-interaction" class="cover-subtitle"><strong class="aboutuswelcome">Terms of Use<br></strong></div>
      <div data-ix="new-interaction-2" class="cover-cta"><a href="../recipes.php" class="button-cta secondary w-button" data-ix="cover-title-appear"><strong class="bold-text-3">View Our Delicious Holiday Recepies</strong></a><a href="#" data-ix="cover-title-appear-2-scroll" class="go-down-link paddingfixforarrow w-inline-block"><img src="../images/5a0df63d70c9e80001f55fed_white-down-arrow-png-211-compressor.png" width="50" data-ix="arrowhovereffect" alt=""></a></div>
    </div>
  </div>
  <div id="Section-2" class="mainsectionterms dark _1st">
    <div class="termsbodywrapper">
      <h1 class="termsheader1">Terms of Use &amp; services</h1>
      <h1 class="termsheader2">1. ACCEPTANCE OF TERMS.<br></h1>
      <p class="termsparagraph"><strong><em>This website (the &quot;Website&quot;) is owned and operated by EL SEMBRADOR, Corp., on behalf of EL SEMBRADOR, and its affiliates (the &quot;Company,&quot; &quot;Us&quot; or &quot;We&quot;). Access to and use of the Website are subject to the terms and conditions of this Terms of Use and Privacy Policy, and all applicable laws and regulations, including laws and regulations governing copyright and trademark. &quot;Website&quot; includes any method by which we make available information to you, including through email service, another website, or a mobile website or application you have requested. BY ACCESSING THE WEBSITE, YOU ACCEPT, WITHOUT LIMITATION OR QUALIFICATION, ALL OF THE TERMS AND CONDITIONS IN THIS USER AGREEMENT INCLUDING ALL OF THE DISCLAIMERS BELOW. We reserve the right to change these terms and conditions at any time. The changes will appear on this screen. By using the Website, you agree in advance to accept any changes as a condition or using the Website.</em></strong></p>
      <h1 class="termsheader2">2. LIMITED LICENSE<br></h1>
      <p class="termsparagraph"><strong><em>The Company permits you to view the Website and to use the information it offers in our sole discretion, under a limited, non-transferable, non-exclusive license, provided that you shall only use the Website and information it offers on a personal, non-commercial basis, for the purposes for which we offer it to you.<br></em></strong></p>
      <h1 class="termsheader2">3. TRADEMARKS AND COPYRIGHTS<br></h1>
      <p class="termsparagraph"><strong><em>The materials on this Web site are copyrighted and protected by worldwide copyright laws and treaty provisions. Any unauthorized use of these materials may violate copyright, trademark and other laws. Materials on this Web site may not be copied, reproduced, modified, published, uploaded, posted, transmitted, or distributed in any way without the prior written permission of Company. Except as expressly provided, Company does not grant any express or implied right to you under any patents, copyrights, trademarks, or trade secrets.<br><br></em></strong></p>
      <h1 class="termsheader2">4. NO WARRANTIES OF ACCURACY OR ENDORSEMENT OF INFORMATION<br></h1>
      <p class="termsparagraph"><strong><em>As an informational service to its customers and others who view this Website, we provide educational articles on a range of subjects, including health, nutrition and fitness. Although Company has attempted to provide accurate information, we assume no responsibility for, and make no representation regarding, the accuracy of the information presented on the Website. Moreover, Company does not represent or endorse the accuracy or reliability of any advice, opinion, statement, or other information displayed, uploaded, or distributed through the Website by any user, information provider or any other person or entity, including medical and other professionals who author posted articles. Nor do we represent or warrant the accuracy of the credentials or identity any person posting information on the Website. You acknowledge that any reliance upon any such opinion, advice, statement, memorandum, or information shall be at your sole risk.<br><br></em></strong></p>
      <h1 class="termsheader2">5. DISCLAIMERS<br></h1>
      <p class="termsparagraph"><strong><em>ALL INFORMATION PROVIDED ON THIS WEBSITE IS PROVIDED TO YOU ON AN &quot;AS IS&quot; BASIS, WITHOUT WARRANTY OF ANY KIND EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. COMPANY MAKES NO WARRANTY AS TO THE ACCURACY, COMPLETENESS, CURRENCY, OR RELIABILITY OF ANY CONTENT AVAILABLE THROUGH THIS WEBSITE. YOU ARE RESPONSIBLE FOR VERIFYING ANY INFORMATION BEFORE RELYING ON IT. USE OF THE WEBSITE AND THE CONTENT AVAILABLE ON THE WEBSITE IS AT YOUR SOLE RISK. COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES THAT USE OF THE WEBSITE WILL BE SECURE, UNINTERRUPTED OR ERROR-FREE.<br><br></em></strong></p>
      <h1 class="termsheader2">6. MEDICAL, NUTRITION AND HEALTH ADVICE DISCLAIMER<br></h1>
      <p class="termsparagraph"><strong><em>THE WEBSITE MAY OFFER HEALTH, FITNESS AND NUTRITIONAL INFORMATION, WHICH IS DESIGNED FOR EDUCATIONAL PURPOSES ONLY. YOU SHOULD CONSULT YOUR PHYSICIAN OR CARE PROVIDER BEFORE BEGINNING A NEW NUTRITIONAL OR FITNESS PROGRAM. YOU SHOULD NOT RELY ON ANY INFORMATION ON THE SITE AS, OR AS A SUBSTITUTE FOR PROFESSIONAL MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT. IF YOU HAVE ANY CONCERNS OR QUESTIONS ABOUT YOUR HEALTH, YOU SHOULD ALWAYS CONSULT WITH A PHYSICIAN OR OTHER HEALTH-CARE PROFESSIONAL. DO NOT DISREGARD, AVOID OR DELAY OBTAINING MEDICAL OR HEALTH RELATED ADVICE FROM YOUR HEALTH-CARE PROFESSIONAL BECAUSE OF SOMETHING YOU MAY HAVE READ ON THE WEBSITE. THE USE OF ANY INFORMATION PROVIDED ON THE WEBSITE IS SOLELY AT YOUR OWN RISK.<br><br></em></strong></p>
      <h1 class="termsheader2">7. OUR PRIVACY POLICY.<br></h1>
      <p class="termsparagraph"><strong><em>Our Privacy Policy, which is found below, contains further information about how we collect, use and share information from our Website. We recommend that you read it. Any information you submit to us on the Website or a related service, including through any contest, sweepstakes or promotion, is subject to the Privacy Policy.<br><br></em></strong></p>
      <h1 class="termsheader2">8. NO SUBMISSION OF DATA BY PERSONS UNDER THE AGE OF THIRTEEN.<br></h1>
      <p class="termsparagraph"><strong><em>It is our policy not to solicit or knowingly accept any personal information from any person under the age of thirteen (13). If you are under 13, do not submit or send any information to us, including without limitation your name, address, email address, or information of any other type.<br></em></strong></p>
      <h1 class="termsheader2">9. LIMITATION OF LIABILITY<br></h1>
      <p class="termsparagraph"><strong><em>COMPANY SPECIFICALLY DISCLAIMS ANY LIABILITY, WHETHER BASED IN CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR SPECIAL DAMAGES ARISING OUT OF OR IN ANY WAY CONNECTED WITH ACCESS TO OR USE OF THE WEBSITE, EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, INCLUDING BUT NOT LIMITED TO RELIANCE BY ANY PARTY ON ANY CONTENT OBTAINED THROUGH THE USE OF THIS WEB SITE, WHETHER CAUSED IN WHOLE OR IN PART BY NEGLIGENCE, ACTS OF GOD, TELECOMMUNICATIONS FAILURE, THEFT OR DESTRUCTION OF OR UNAUTHORIZED ACCESS TO THE WEB SITE, OR RELATED INFORMATION OR PROGRAMS.<br><br></em></strong></p>
      <h1 class="termsheader2">10. CONTESTS, SWEEPSTAKES AND PROMOTIONS<br></h1>
      <p class="termsparagraph"><strong><em>We or a partner we engage may operate contests, sweepstakes or promotions from or on the Website. You must agree to and abide by all terms and conditions of such promotions, and must be eighteen (18) years of age or over in order to participate and win.<br><br></em></strong></p>
      <h1 class="termsheader2">11. NO SUBMISSION OF UNSOLICITED IDEAS<br></h1>
      <p class="termsparagraph"><strong><em>Company does not accept unsolicited ideas of any kind, including ideas for: advertising; promotions; new products, technologies, processes, or materials; marketing plans; or product names. Please do not send us any such ideas or materials relating to such ideas. This is to avoid any potential misunderstanding or dispute should our products or marketing strategies seem similar to unsolicited ideas submitted to us. If, despite this request, you do send us any unsolicited ideas or materials, we make no assurances that such ideas or materials will be treated as confidential or proprietary.<br><br></em></strong></p>
      <h1 class="termsheader2">12. LINKS TO THIRD PARTY SITES<br></h1>
      <p class="termsparagraph"><strong><em>This Web site may contain links to third party sites. Access to any other website or service linked to this Web site is at the user&#x27;s own risk and Company is not responsible for the accuracy or reliability of any information, data, opinions, advice or statements made on these sites. Company provides these links merely as a convenience and does not endorse the companies or contents of any linked sites.<br><br></em></strong></p>
      <h1 class="termsheader2">13. APPLICABLE LAW<br></h1>
      <p class="termsparagraph"><strong><em>The laws applicable to the interpretation of these terms shall be federal law of the United States and the laws of the State of New York, without regard to any conflict of law principles or provisions. If any provision within these terms is held to be invalid or unenforceable, such provision shall be struck and all remaining provisions shall be enforced.<br><br></em></strong></p>
      <h1 class="termsheader2">14. COUPONS<br></h1>
      <p class="termsparagraph"><strong><em>All our vendor Supermarkets are individually owned and operated and have their own policies regarding acceptance of coupons. Please see individual stores for further details.<br></em></strong></p>
      <h1 class="termsheader2">15. GENERAL<br></h1>
      <p class="termsparagraph"><strong><em>You agree that we may revise these legal terms at any time by updating this posting. You should visit this page from time to time to review the then-current terms. Certain provisions of these Legal terms may be superseded by expressly designated legal notices or terms located on particular pages on this Website.<br></em></strong></p>
    </div>
    <div data-ix="new-interaction-2" class="cover-cta"><a href="../recipes.php" class="button-cta secondary w-button" data-ix="cover-title-appear"><strong class="bold-text-3">Delicious holiday recipes</strong></a></div>
  </div>
  
<?php include $_SERVER['DOCUMENT_ROOT']."/includes/footer.php" ?>