<?php include $_SERVER['DOCUMENT_ROOT']."/includes/header.php"; ?>


  <div id="coverSection" class="coversectionaboutus">
    <div class="covercontainerprimary w-container">
      <div data-ix="new-interaction" class="cover-subtitle"><strong class="aboutuswelcome">Privacy Policy</strong></div>
      <div data-ix="new-interaction-2" class="cover-cta"><a href="#Section-2" class="button-cta secondary w-button" data-ix="cover-title-appear"><strong class="bold-text-3">View Our Delicious Holiday Recepies</strong></a><a href="#" data-ix="cover-title-appear-2-scroll" class="go-down-link paddingfixforarrow w-inline-block"><img src="../images/5a0df63d70c9e80001f55fed_white-down-arrow-png-211-compressor.png" width="50" data-ix="arrowhovereffect" alt=""></a></div>
    </div>
  </div>
  <div id="Section-2" class="mainsectionterms dark _1st">
    <div class="termsbodywrapper">
      <h1 class="termsheader1">Our Privacy Policy</h1>
      <h1 class="termsheader2">OUR INFORMATION COLLECTION &amp; USE<br><br></h1>
      <p class="termsparagraph"><strong><em>We take your privacy seriously. Please take a moment to read this Privacy Policy, which discloses the privacy practices of the Website and services described in our Terms of Service. Specifically, this Privacy Policy outlines the types of information that information may be gathered when you register for or use the Website, our newsletters, or other services we may provide, and the ways in which that information may be used.<br></em></strong></p>
      <h1 class="termsheader2">1. INFORMATION YOU GIVE US<br></h1>
      <p class="termsparagraph"><strong><em>To enable you to enjoy certain features of our Website, we collect certain types of information, including personally identifiable information. For example, we collect information when you:<br></em></strong></p>
      <ul class="termsul">
        <li class="termslicontent"><strong class="termsliheader">Sign up to receive email newsletters:<br>‍</strong>When you register to receive a newsletter or other communication, we may ask you to provide certain information, which may include your email address, home address, birth year, gender or zip code, as well as a password for your account. Except as described in this Privacy Policy, we will not provide unaffiliated parties access to this personal information, without your permission.<br><br>When we send newsletters to subscribers we may allow our advertisers or other marketing partners to include messages, offers or coupons in those newsletters, or we may send dedicated newsletters on their behalf. To unsubscribe from a particular newsletter, click the &quot;unsubscribe&quot; link at the bottom of that email newsletter.</li>
        <li class="termslicontent"><strong class="termsliheader">Contests, Sweepstakes and Special Offers.<br>‍</strong>We may sponsor contests, sweepstakes, or promote special offers on the Website or on third party sites. If you elect to participate, we may require personal information from you including, in most cases, your first and last name and e-mail address. If this information is also being collected by a third party, we will notify you at the time of collection. If you do not want any personal information shared, you may always decline to participate in the sweepstakes, contest or special offers.<br></li>
      </ul>
      <h1 class="termsheader2">2. INFORMATION WE COLLECT USING TECHNOLOGY<br></h1>
      <ul class="termsul">
        <li class="termslicontent"><strong class="termsliheader">Device Information:<br>‍</strong>We may collect information about the browser, computer, mobile telephone, smartphone or other device you use to access the Website, to measure the effectiveness of the Website or content we deliver.</li>
        <li class="termslicontent"><strong class="termsliheader">Cookies:<br>‍</strong>As further explained in Section 3 below, we may use cookies, pixel trackers, server logs, and any Internet technology in order to measure the effectiveness of our content, Website and any advertising campaigns, as well as to target meaningful content and ads to our users and customers.<br></li>
        <li class="termslicontent"><strong class="termsliheader">Analytics:<br>‍</strong>We may use third parties to provide us information, reports and analysis about the usage and browsing patterns of users of the Website and/or our customers. These reports contain aggregated data only, and do not identify individual users.<br></li>
        <li class="termslicontent"><strong class="termsliheader">IP Addresses:<br>‍</strong>We log Internet Protocol (IP) addresses, or the location of your computer on the Internet, for systems administration and troubleshooting purposes. We use this information in an aggregate fashion to track access to our Website.<br></li>
        <li class="termslicontent"><strong class="termsliheader">Log Files:<br>‍</strong>We may also automatically log certain usage information about your use of the Website. This information includes a reading history of the pages you view.<br></li>
      </ul>
      <h1 class="termsheader2">3. COOKIES, WEB BEACONS, AND SIMILAR TECHNOLOGIES<br></h1>
      <p class="termsparagraph"><strong><em>Like many websites, and web and mobile service, we may use (or work with third party partners who use) a variety of technologies to learn more about how people interact with us. This section provides more information about some of those technologies and how they work.<br></em></strong></p>
      <ul class="termsul">
        <li class="termslicontent"><strong class="termsliheader">Cookies:<br>‍</strong>Cookies are small text files that websites and other online services use to store information about users on the users&#x27; own computers. Cookies can be used to store sign-in credentials so that you don&#x27;t have to enter them each time you return to a website, or to store other information to make web viewing more customized or efficient upon future visits. Cookies also may store a unique identifier tied to your computer so that web services and advertising networks can recognize you across visits to different websites. You can configure your Internet browser to warn you each time a cookie is being sent or to refuse all or certain cookies completely.<br><br>We may use or support cookies as follows:<br>‍<br></li>
        <li class="termslicontent"><strong class="termsliheader">‍</strong>To collect information about your browsing activities in order to deliver customized or relevant services, advertising or content to you;<br></li>
        <li class="termslicontent"><strong class="termsliheader">‍</strong>To relate the information collected by cookies to information we obtain from you directly or from commercially available sources;<br></li>
        <li class="termslicontent"><strong class="termsliheader">‍</strong>To work with third parties that serve advertisements (through our Website or across the Internet) or provide other services to us, such as providing users the ability to comment on content, allowing users to share content, or tracking site usage statistics. We do not control these third party technologies and their use is governed by the privacy policies of the third parties using such technologies.<br><br>For more information about third party ad networks and services that use these technologies, see www.aboutads.info., and to opt out of such ad networks&#x27; and services&#x27; collection and advertising practices, go to http://aboutads.info/choices.<br></li>
      </ul>
      <h1 class="termsheader2">4. HOW WE USE THE INFORMATION WE COLLECT<br></h1>
      <p class="termsparagraph"><strong><em>We may collect, store and process the information we receive from you for the following purposes:<br></em></strong></p>
      <ul class="termsul">
        <li class="termslicontent"><strong class="termsliheader">Providing the Services You Request:<br>‍</strong>We use the information we gather about you to enable your use of the Website and the information or offers you request, fulfill your requests for certain products and services, such as sending out electronic newsletters and enabling you to participate in polls, contests, and (in our discretion) message boards. We reserve the right to disclose your opt-out information to third parties so they can suppress your name from future solicitations, in accordance with applicable laws.<br></li>
        <li class="termslicontent"><strong class="termsliheader">Statistical Analysis:<br>‍</strong>We use the information, including analytics and statistical information, to analyze your use of the Website so that we may improve it and our products and services. We also may use this information to generally inform advertisers about the nature of our user base.<br></li>
        <li class="termslicontent"><strong class="termsliheader">Customizing Your Experience:<br>‍</strong>We may use the information that we collect to allow advertising to be targeted to the users for whom such advertising is most pertinent.<br></li>
        <li class="termslicontent"><strong class="termsliheader">Service Providers:<br>‍</strong>We may contract with other companies to provide services on our behalf, including credit-card and billing processing, survey administrators, technical or customer support, shipping, e-mail distribution, email service providers, data enhancement providers, list processing and promotions management. We provide these companies only with the information they need to perform their services. These service providers are restricted from using this data in any way other than to provide services for us, and they may not share, resell or use the data for their own marketing purposes.<br><br>‍<br></li>
      </ul>
      <h1 class="termsheader2">5. OUR AFFILIATES<br></h1>
      <p class="termsparagraph"><strong><em> Included but not limited to are all affiliates (Publix, Sedanos, Walmart, Presedente, Kroger, Sam&#x27;s Club, Winn Dixie, &amp; Bravo), may share information they have collected (included information collected on this Website) with each other, and with their marketing entity. These entities may share general information collected, for instance, to better understand our respective users (their demographics, what they do on our websites, what products they like, etc.) and to improve the content on this Website.<br><br></em></strong></p>
      <h1 class="termsheader2">6. INFORMATION FROM CHILDREN UNDER 13<br></h1>
      <p class="termsparagraph"><strong><em>We do not knowingly collect any personally identifiable information from children under the age of 13. If we determine that a user is under 13, we will delete all information pertaining to that user.<br></em></strong></p>
      <h1 class="termsheader2">7. COMPLIANCE WITH LEGAL PROCESS<br></h1>
      <p class="termsparagraph"><strong><em>We may disclose personal information if we are required to do so by law.<br><br></em></strong></p>
    </div>
    <div data-ix="new-interaction-2" class="cover-cta"><a href="../recipes.php" class="button-cta secondary w-button" data-ix="cover-title-appear"><strong class="bold-text-3">Delicious holiday recipes</strong></a></div>
  </div>
  
<?php include $_SERVER['DOCUMENT_ROOT']."/includes/footer.php" ?>